package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// logErr outputs errors to Stderr to keep standard output clean
func logErr(format string, a ...interface{}) {
	fmt.Fprintf(os.Stderr, "Error: "+format+"\n", a...)
}

func main() {
	typeName := flag.String("type", "", "name of the type to generate collections for")
	flag.Parse()

	if *typeName == "" {
		logErr("-type flag is required")
		os.Exit(1)
	}

	gofile := os.Getenv("GOFILE")
	if gofile == "" {
		logErr("GOFILE environment variable not set. Run via 'go generate'")
		os.Exit(1)
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, gofile, nil, parser.ParseComments)
	if err != nil {
		logErr("Failed to parse file %s: %v", gofile, err)
		os.Exit(1)
	}

	var constants []string
	ast.Inspect(node, func(n ast.Node) bool {
		decl, ok := n.(*ast.GenDecl)
		if !ok || decl.Tok != token.CONST {
			return true
		}

		for _, spec := range decl.Specs {
			vSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			// Check if the constant explicitly matches our target type
			isTargetType := false
			if vSpec.Type != nil {
				if ident, ok := vSpec.Type.(*ast.Ident); ok && ident.Name == *typeName {
					isTargetType = true
				}
			}

			if isTargetType {
				for _, name := range vSpec.Names {
					constants = append(constants, name.Name)
				}
			}
		}
		return true
	})

	if len(constants) == 0 {
		logErr("No constants found for type %s in file %s", *typeName, gofile)
		os.Exit(0)
	}

	// Generate the companion code
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("// Code generated by strenum; DO NOT EDIT.\n\npackage %s\n\n", node.Name.Name))

	// 1. Generate the Slice
	buf.WriteString(fmt.Sprintf("var _All%s = []%s{\n", *typeName, *typeName))
	for _, c := range constants {
		buf.WriteString(fmt.Sprintf("\t%s,\n", c))
	}
	buf.WriteString("}\n\n")

	// 2. Generate the Map
	buf.WriteString(fmt.Sprintf("var _%sMap = map[%s]struct{}{\n", *typeName, *typeName))
	for _, c := range constants {
		buf.WriteString(fmt.Sprintf("\t%s: {},\n", c))
	}
	buf.WriteString("}\n\n")

	// 3. Generate Helper Methods
	buf.WriteString(fmt.Sprintf("func %sValues() []%s {\n\treturn _All%s\n}\n\n", *typeName, *typeName, *typeName))
	buf.WriteString(fmt.Sprintf("func (x %s) IsValid() bool {\n\t_, ok := _%sMap[x]\n\treturn ok\n}\n", *typeName, *typeName))

	ext := filepath.Ext(gofile)
	base := strings.TrimSuffix(gofile, ext)
	outputFile := fmt.Sprintf("%s_%s_gen.go", base, strings.ToLower(*typeName))

	err = os.WriteFile(outputFile, buf.Bytes(), 0644)
	if err != nil {
		logErr("Failed to write output file %s: %v", outputFile, err)
		os.Exit(1)
	}

	// Success feedback
	fmt.Printf("Generated: %s (%d constants found)\n", outputFile, len(constants))
}
