// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	bean "github.com/devtron-labs/git-sensor/bean"
	git "github.com/devtron-labs/git-sensor/pkg/git"
	mock "github.com/stretchr/testify/mock"

	pkg "github.com/devtron-labs/git-sensor/pkg"

	sql "github.com/devtron-labs/git-sensor/internals/sql"
)

// RepoManager is an autogenerated mock type for the RepoManager type
type RepoManager struct {
	mock.Mock
}

// AddRepo provides a mock function with given fields: gitCtx, material
func (_m *RepoManager) AddRepo(gitCtx git.GitContext, material []*sql.GitMaterial) ([]*sql.GitMaterial, error) {
	ret := _m.Called(gitCtx, material)

	var r0 []*sql.GitMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, []*sql.GitMaterial) ([]*sql.GitMaterial, error)); ok {
		return rf(gitCtx, material)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, []*sql.GitMaterial) []*sql.GitMaterial); ok {
		r0 = rf(gitCtx, material)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sql.GitMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, []*sql.GitMaterial) error); ok {
		r1 = rf(gitCtx, material)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchChanges provides a mock function with given fields: gitCtx, pipelineMaterialId, from, to, count, showAll
func (_m *RepoManager) FetchChanges(gitCtx git.GitContext, pipelineMaterialId int, from string, to string, count int, showAll bool) (*git.MaterialChangeResp, error) {
	ret := _m.Called(gitCtx, pipelineMaterialId, from, to, count, showAll)

	var r0 *git.MaterialChangeResp
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string, string, int, bool) (*git.MaterialChangeResp, error)); ok {
		return rf(gitCtx, pipelineMaterialId, from, to, count, showAll)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string, string, int, bool) *git.MaterialChangeResp); ok {
		r0 = rf(gitCtx, pipelineMaterialId, from, to, count, showAll)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.MaterialChangeResp)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, int, string, string, int, bool) error); ok {
		r1 = rf(gitCtx, pipelineMaterialId, from, to, count, showAll)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllWebhookEventConfigForHost provides a mock function with given fields: gitCtx, req
func (_m *RepoManager) GetAllWebhookEventConfigForHost(gitCtx git.GitContext, req *git.WebhookEventConfigRequest) ([]*git.WebhookEventConfig, error) {
	ret := _m.Called(gitCtx, req)

	var r0 []*git.WebhookEventConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.WebhookEventConfigRequest) ([]*git.WebhookEventConfig, error)); ok {
		return rf(gitCtx, req)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.WebhookEventConfigRequest) []*git.WebhookEventConfig); ok {
		r0 = rf(gitCtx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*git.WebhookEventConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *git.WebhookEventConfigRequest) error); ok {
		r1 = rf(gitCtx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommitInfoForTag provides a mock function with given fields: gitCtx, request
func (_m *RepoManager) GetCommitInfoForTag(gitCtx git.GitContext, request *git.CommitMetadataRequest) (*git.GitCommitBase, error) {
	ret := _m.Called(gitCtx, request)

	var r0 *git.GitCommitBase
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.CommitMetadataRequest) (*git.GitCommitBase, error)); ok {
		return rf(gitCtx, request)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.CommitMetadataRequest) *git.GitCommitBase); ok {
		r0 = rf(gitCtx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.GitCommitBase)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *git.CommitMetadataRequest) error); ok {
		r1 = rf(gitCtx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommitMetadata provides a mock function with given fields: gitCtx, pipelineMaterialId, gitHash
func (_m *RepoManager) GetCommitMetadata(gitCtx git.GitContext, pipelineMaterialId int, gitHash string) (*git.GitCommitBase, error) {
	ret := _m.Called(gitCtx, pipelineMaterialId, gitHash)

	var r0 *git.GitCommitBase
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string) (*git.GitCommitBase, error)); ok {
		return rf(gitCtx, pipelineMaterialId, gitHash)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string) *git.GitCommitBase); ok {
		r0 = rf(gitCtx, pipelineMaterialId, gitHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.GitCommitBase)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, int, string) error); ok {
		r1 = rf(gitCtx, pipelineMaterialId, gitHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommitMetadataForPipelineMaterial provides a mock function with given fields: gitCtx, pipelineMaterialId, gitHash
func (_m *RepoManager) GetCommitMetadataForPipelineMaterial(gitCtx git.GitContext, pipelineMaterialId int, gitHash string) (*git.GitCommitBase, error) {
	ret := _m.Called(gitCtx, pipelineMaterialId, gitHash)

	var r0 *git.GitCommitBase
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string) (*git.GitCommitBase, error)); ok {
		return rf(gitCtx, pipelineMaterialId, gitHash)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string) *git.GitCommitBase); ok {
		r0 = rf(gitCtx, pipelineMaterialId, gitHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.GitCommitBase)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, int, string) error); ok {
		r1 = rf(gitCtx, pipelineMaterialId, gitHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHeadForPipelineMaterials provides a mock function with given fields: gitCtx, ids
func (_m *RepoManager) GetHeadForPipelineMaterials(gitCtx git.GitContext, ids []int) ([]*git.CiPipelineMaterialBean, error) {
	ret := _m.Called(gitCtx, ids)

	var r0 []*git.CiPipelineMaterialBean
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, []int) ([]*git.CiPipelineMaterialBean, error)); ok {
		return rf(gitCtx, ids)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, []int) []*git.CiPipelineMaterialBean); ok {
		r0 = rf(gitCtx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*git.CiPipelineMaterialBean)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, []int) error); ok {
		r1 = rf(gitCtx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestCommitForBranch provides a mock function with given fields: gitCtx, pipelineMaterialId, branchName
func (_m *RepoManager) GetLatestCommitForBranch(gitCtx git.GitContext, pipelineMaterialId int, branchName string) (*git.GitCommitBase, error) {
	ret := _m.Called(gitCtx, pipelineMaterialId, branchName)

	var r0 *git.GitCommitBase
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string) (*git.GitCommitBase, error)); ok {
		return rf(gitCtx, pipelineMaterialId, branchName)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, int, string) *git.GitCommitBase); ok {
		r0 = rf(gitCtx, pipelineMaterialId, branchName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.GitCommitBase)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, int, string) error); ok {
		r1 = rf(gitCtx, pipelineMaterialId, branchName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReleaseChanges provides a mock function with given fields: gitCtx, request
func (_m *RepoManager) GetReleaseChanges(gitCtx git.GitContext, request *pkg.ReleaseChangesRequest) (*git.GitChanges, error) {
	ret := _m.Called(gitCtx, request)

	var r0 *git.GitChanges
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *pkg.ReleaseChangesRequest) (*git.GitChanges, error)); ok {
		return rf(gitCtx, request)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *pkg.ReleaseChangesRequest) *git.GitChanges); ok {
		r0 = rf(gitCtx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.GitChanges)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *pkg.ReleaseChangesRequest) error); ok {
		r1 = rf(gitCtx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebhookAndCiDataById provides a mock function with given fields: gitCtx, id, ciPipelineMaterialId
func (_m *RepoManager) GetWebhookAndCiDataById(gitCtx git.GitContext, id int, ciPipelineMaterialId int) (*git.WebhookAndCiData, error) {
	ret := _m.Called(gitCtx, id, ciPipelineMaterialId)

	var r0 *git.WebhookAndCiData
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, int, int) (*git.WebhookAndCiData, error)); ok {
		return rf(gitCtx, id, ciPipelineMaterialId)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, int, int) *git.WebhookAndCiData); ok {
		r0 = rf(gitCtx, id, ciPipelineMaterialId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.WebhookAndCiData)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, int, int) error); ok {
		r1 = rf(gitCtx, id, ciPipelineMaterialId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebhookEventConfig provides a mock function with given fields: gitCtx, eventId
func (_m *RepoManager) GetWebhookEventConfig(gitCtx git.GitContext, eventId int) (*git.WebhookEventConfig, error) {
	ret := _m.Called(gitCtx, eventId)

	var r0 *git.WebhookEventConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, int) (*git.WebhookEventConfig, error)); ok {
		return rf(gitCtx, eventId)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, int) *git.WebhookEventConfig); ok {
		r0 = rf(gitCtx, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.WebhookEventConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, int) error); ok {
		r1 = rf(gitCtx, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebhookPayloadDataForPipelineMaterialId provides a mock function with given fields: gitCtx, request
func (_m *RepoManager) GetWebhookPayloadDataForPipelineMaterialId(gitCtx git.GitContext, request *git.WebhookPayloadDataRequest) (*git.WebhookPayloadDataResponse, error) {
	ret := _m.Called(gitCtx, request)

	var r0 *git.WebhookPayloadDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.WebhookPayloadDataRequest) (*git.WebhookPayloadDataResponse, error)); ok {
		return rf(gitCtx, request)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.WebhookPayloadDataRequest) *git.WebhookPayloadDataResponse); ok {
		r0 = rf(gitCtx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.WebhookPayloadDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *git.WebhookPayloadDataRequest) error); ok {
		r1 = rf(gitCtx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebhookPayloadFilterDataForPipelineMaterialId provides a mock function with given fields: gitCtx, request
func (_m *RepoManager) GetWebhookPayloadFilterDataForPipelineMaterialId(gitCtx git.GitContext, request *git.WebhookPayloadFilterDataRequest) (*git.WebhookPayloadFilterDataResponse, error) {
	ret := _m.Called(gitCtx, request)

	var r0 *git.WebhookPayloadFilterDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.WebhookPayloadFilterDataRequest) (*git.WebhookPayloadFilterDataResponse, error)); ok {
		return rf(gitCtx, request)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.WebhookPayloadFilterDataRequest) *git.WebhookPayloadFilterDataResponse); ok {
		r0 = rf(gitCtx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.WebhookPayloadFilterDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *git.WebhookPayloadFilterDataRequest) error); ok {
		r1 = rf(gitCtx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshGitMaterial provides a mock function with given fields: gitCtx, req
func (_m *RepoManager) RefreshGitMaterial(gitCtx git.GitContext, req *git.RefreshGitMaterialRequest) (*git.RefreshGitMaterialResponse, error) {
	ret := _m.Called(gitCtx, req)

	var r0 *git.RefreshGitMaterialResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.RefreshGitMaterialRequest) (*git.RefreshGitMaterialResponse, error)); ok {
		return rf(gitCtx, req)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *git.RefreshGitMaterialRequest) *git.RefreshGitMaterialResponse); ok {
		r0 = rf(gitCtx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.RefreshGitMaterialResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *git.RefreshGitMaterialRequest) error); ok {
		r1 = rf(gitCtx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReloadAllRepo provides a mock function with given fields: gitCtx, req
func (_m *RepoManager) ReloadAllRepo(gitCtx git.GitContext, req *bean.ReloadAllMaterialQuery) error {
	ret := _m.Called(gitCtx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *bean.ReloadAllMaterialQuery) error); ok {
		r0 = rf(gitCtx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetRepo provides a mock function with given fields: gitCtx, materialId
func (_m *RepoManager) ResetRepo(gitCtx git.GitContext, materialId int) error {
	ret := _m.Called(gitCtx, materialId)

	var r0 error
	if rf, ok := ret.Get(0).(func(git.GitContext, int) error); ok {
		r0 = rf(gitCtx, materialId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveGitProvider provides a mock function with given fields: gitCtx, provider
func (_m *RepoManager) SaveGitProvider(gitCtx git.GitContext, provider *sql.GitProvider) (*sql.GitProvider, error) {
	ret := _m.Called(gitCtx, provider)

	var r0 *sql.GitProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *sql.GitProvider) (*sql.GitProvider, error)); ok {
		return rf(gitCtx, provider)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *sql.GitProvider) *sql.GitProvider); ok {
		r0 = rf(gitCtx, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.GitProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *sql.GitProvider) error); ok {
		r1 = rf(gitCtx, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SavePipelineMaterial provides a mock function with given fields: gitCtx, material
func (_m *RepoManager) SavePipelineMaterial(gitCtx git.GitContext, material []*sql.CiPipelineMaterial) ([]*sql.CiPipelineMaterial, error) {
	ret := _m.Called(gitCtx, material)

	var r0 []*sql.CiPipelineMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, []*sql.CiPipelineMaterial) ([]*sql.CiPipelineMaterial, error)); ok {
		return rf(gitCtx, material)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, []*sql.CiPipelineMaterial) []*sql.CiPipelineMaterial); ok {
		r0 = rf(gitCtx, material)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sql.CiPipelineMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, []*sql.CiPipelineMaterial) error); ok {
		r1 = rf(gitCtx, material)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRepo provides a mock function with given fields: gitCtx, material
func (_m *RepoManager) UpdateRepo(gitCtx git.GitContext, material *sql.GitMaterial) (*sql.GitMaterial, error) {
	ret := _m.Called(gitCtx, material)

	var r0 *sql.GitMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(git.GitContext, *sql.GitMaterial) (*sql.GitMaterial, error)); ok {
		return rf(gitCtx, material)
	}
	if rf, ok := ret.Get(0).(func(git.GitContext, *sql.GitMaterial) *sql.GitMaterial); ok {
		r0 = rf(gitCtx, material)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.GitMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(git.GitContext, *sql.GitMaterial) error); ok {
		r1 = rf(gitCtx, material)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepoManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepoManager creates a new instance of RepoManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepoManager(t mockConstructorTestingTNewRepoManager) *RepoManager {
	mock := &RepoManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
