// Code generated by strenum; DO NOT EDIT.

package audit

var _AllAuditModule = []AuditModule{
	ModuleAppManagement,
	ModuleInfrastructureManagement,
	ModuleCostVisibility,
	ModuleSoftwareDistributionHub,
	ModuleGlobalConfiguration,
	ModuleUserManagement,
}

var _AuditModuleMap = map[AuditModule]struct{}{
	ModuleAppManagement: {},
	ModuleInfrastructureManagement: {},
	ModuleCostVisibility: {},
	ModuleSoftwareDistributionHub: {},
	ModuleGlobalConfiguration: {},
	ModuleUserManagement: {},
}

func AuditModuleValues() []AuditModule {
	return _AllAuditModule
}

func (x AuditModule) IsValid() bool {
	_, ok := _AuditModuleMap[x]
	return ok
}
