// Code generated by strenum; DO NOT EDIT.

package audit

var _AllAuditAction = []AuditAction{
	ActionCreate,
	ActionUpdate,
	ActionDelete,
	ActionTrigger,
	ActionDeploy,
	ActionHibernate,
	ActionUnHibernate,
	ActionRollback,
	ActionSync,
	ActionApprove,
	ActionClone,
	ActionAssign,
	ActionGet,
	ActionExec,
	ActionApply,
}

var _AuditActionMap = map[AuditAction]struct{}{
	ActionCreate: {},
	ActionUpdate: {},
	ActionDelete: {},
	ActionTrigger: {},
	ActionDeploy: {},
	ActionHibernate: {},
	ActionUnHibernate: {},
	ActionRollback: {},
	ActionSync: {},
	ActionApprove: {},
	ActionClone: {},
	ActionAssign: {},
	ActionGet: {},
	ActionExec: {},
	ActionApply: {},
}

func AuditActionValues() []AuditAction {
	return _AllAuditAction
}

func (x AuditAction) IsValid() bool {
	_, ok := _AuditActionMap[x]
	return ok
}
