name: golangci-lint
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:    
      - 'main'
      - 'rc-*'
      - 'hotfix-*'
      - 'develop'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: [common-lib, authenticator, chart-sync,kubewatch,git-sensor,kubelink,lens]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - if: ${{ matrix.working-directory=='common-lib' }}
        run: cd common-lib &&  go get oras.land/oras-go/pkg/auth/docker && go mod tidy && go mod download && go mod vendor
        name: installing oras.land package for common-lib

      - name: golangci-lint-${{ matrix.working-directory }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=30m --tests=false --verbose
          only-new-issues: "true"
          working-directory: ${{ matrix.working-directory }}
